// Product data with comprehensive seafood catalog
const products = [
    // Shrimp Products (1-25)
    { id: 1, name: "جمبري جامبو طازج", category: "shrimp", image: "images/product1.jpg", description: "جمبري جامبو طازج عالي الجودة، مثالي للشوي والقلي" },
    { id: 2, name: "جمبري متوسط مقشر", category: "shrimp", image: "images/product2.jpg", description: "جمبري متوسط الحجم مقشر وجاهز للطبخ" },
    { id: 3, name: "جمبري صغير للسلطات", category: "shrimp", image: "images/product3.jpg", description: "جمبري صغير مثالي للسلطات والمقبلات" },
    { id: 4, name: "جمبري بالقشر طازج", category: "shrimp", image: "images/product4.jpg", description: "جمبري طازج بالقشر محفوظ في أفضل ظروف التبريد" },
    { id: 5, name: "جمبري مجمد فاخر", category: "shrimp", image: "images/product5.jpg", description: "جمبري مجمد بتقنية التجميد السريع للحفاظ على النضارة" },
    { id: 6, name: "جمبري تايجر كبير", category: "shrimp", image: "images/product6.jpg", description: "جمبري تايجر كبير الحجم مستورد عالي الجودة" },
    { id: 7, name: "جمبري أبيض طازج", category: "shrimp", image: "images/product7.jpg", description: "جمبري أبيض طازج من البحر الأبيض المتوسط" },
    { id: 8, name: "جمبري وردي فاخر", category: "shrimp", image: "images/product8.jpg", description: "جمبري وردي فاخر بطعم مميز ولحم طري" },
    { id: 9, name: "جمبري للشوي", category: "shrimp", image: "images/product9.jpg", description: "جمبري كبير مخصص للشوي والباربكيو" },
    { id: 10, name: "جمبري مقلي جاهز", category: "shrimp", image: "images/product10.jpg", description: "جمبري مقلي جاهز للتسخين والتقديم" },
    { id: 11, name: "جمبري بالثوم والزبدة", category: "shrimp", image: "images/product11.jpg", description: "جمبري متبل بالثوم والزبدة جاهز للطبخ" },
    { id: 12, name: "جمبري للباستا", category: "shrimp", image: "images/product12.jpg", description: "جمبري متوسط مثالي لأطباق الباستا" },
    { id: 13, name: "جمبري مدخن", category: "shrimp", image: "images/product13.jpg", description: "جمبري مدخن بطريقة تقليدية لنكهة مميزة" },
    { id: 14, name: "جمبري للسوشي", category: "shrimp", image: "images/product14.jpg", description: "جمبري طازج عالي الجودة مخصص للسوشي" },
    { id: 15, name: "جمبري بالكاري", category: "shrimp", image: "images/product15.jpg", description: "جمبري متبل بالكاري والتوابل الهندية" },
    { id: 16, name: "جمبري للسلطة الروسية", category: "shrimp", image: "images/product16.jpg", description: "جمبري صغير مسلوق جاهز للسلطات" },
    { id: 17, name: "جمبري بالليمون", category: "shrimp", image: "images/product17.jpg", description: "جمبري طازج متبل بالليمون والأعشاب" },
    { id: 18, name: "جمبري للشوربة", category: "shrimp", image: "images/product18.jpg", description: "جمبري صغير مثالي لشوربة المأكولات البحرية" },
    { id: 19, name: "جمبري مقرمش", category: "shrimp", image: "images/product19.jpg", description: "جمبري مغطى بالبقسماط للقلي المقرمش" },
    { id: 20, name: "جمبري بالفلفل الأسود", category: "shrimp", image: "images/product20.jpg", description: "جمبري متبل بالفلفل الأسود والتوابل" },
    { id: 21, name: "جمبري للريزوتو", category: "shrimp", image: "images/product21.jpg", description: "جمبري متوسط مثالي لأطباق الريزوتو" },
    { id: 22, name: "جمبري بالزنجبيل", category: "shrimp", image: "images/product22.jpg", description: "جمبري طازج متبل بالزنجبيل الطازج" },
    { id: 23, name: "جمبري للتمبورا", category: "shrimp", image: "images/product23.jpg", description: "جمبري كبير مخصص للتمبورا اليابانية" },
    { id: 24, name: "جمبري بالأعشاب", category: "shrimp", image: "images/product24.jpg", description: "جمبري متبل بخليط الأعشاب الطازجة" },
    { id: 25, name: "جمبري للسندويتش", category: "shrimp", image: "images/product25.jpg", description: "جمبري صغير مطبوخ جاهز للسندويتشات" },

    // Fish Products (26-60)
    { id: 26, name: "سمك بلطي طازج", category: "fish", image: "images/product26.jpg", description: "سمك بلطي طازج من نهر النيل عالي الجودة" },
    { id: 27, name: "سمك بوري مشوي", category: "fish", image: "images/product27.jpg", description: "سمك بوري طازج مثالي للشوي والقلي" },
    { id: 28, name: "سمك موسى فيليه", category: "fish", image: "images/product28.jpg", description: "فيليه سمك موسى طازج بدون عظم" },
    { id: 29, name: "سمك دنيس طازج", category: "fish", image: "images/product29.jpg", description: "سمك دنيس طازج من البحر الأبيض المتوسط" },
    { id: 30, name: "سمك قاروص كبير", category: "fish", image: "images/product30.jpg", description: "سمك قاروص كبير طازج عالي الجودة" },
    { id: 31, name: "سمك مكرونة طازج", category: "fish", image: "images/product31.jpg", description: "سمك مكرونة طازج غني بالأوميجا 3" },
    { id: 32, name: "سمك تونة طازج", category: "fish", image: "images/product32.jpg", description: "سمك تونة طازج عالي الجودة للسوشي" },
    { id: 33, name: "سمك هامور فاخر", category: "fish", image: "images/product33.jpg", description: "سمك هامور فاخر من البحر الأحمر" },
    { id: 34, name: "سمك شعور طازج", category: "fish", image: "images/product34.jpg", description: "سمك شعور طازج بطعم مميز" },
    { id: 35, name: "سمك ناجل أحمر", category: "fish", image: "images/product35.jpg", description: "سمك ناجل أحمر طازج من البحر الأحمر" },
    { id: 36, name: "سمك برانزينو", category: "fish", image: "images/product36.jpg", description: "سمك برانزينو طازج مستورد عالي الجودة" },
    { id: 37, name: "سمك دوراد ذهبي", category: "fish", image: "images/product37.jpg", description: "سمك دوراد ذهبي طازج بلحم أبيض طري" },
    { id: 38, name: "سمك سردين طازج", category: "fish", image: "images/product38.jpg", description: "سمك سردين طازج غني بالفيتامينات" },
    { id: 39, name: "سمك أنشوجة مملحة", category: "fish", image: "images/product39.jpg", description: "سمك أنشوجة مملحة تقليدية للمقبلات" },
    { id: 40, name: "سمك كود فيليه", category: "fish", image: "images/product40.jpg", description: "فيليه سمك كود طازج بدون عظم" },
    { id: 41, name: "سمك هاليبوت", category: "fish", image: "images/product41.jpg", description: "سمك هاليبوت طازج بلحم أبيض ناعم" },
    { id: 42, name: "سمك ماهي ماهي", category: "fish", image: "images/product42.jpg", description: "سمك ماهي ماهي الاستوائي الطازج" },
    { id: 43, name: "سمك سنابر أحمر", category: "fish", image: "images/product43.jpg", description: "سمك سنابر أحمر طازج عالي الجودة" },
    { id: 44, name: "سمك مارلين", category: "fish", image: "images/product44.jpg", description: "سمك مارلين الفاخر للمناسبات الخاصة" },
    { id: 45, name: "سمك سيف طازج", category: "fish", image: "images/product45.jpg", description: "سمك سيف طازج بلحم كثيف ولذيذ" },
    { id: 46, name: "سمك مرجان", category: "fish", image: "images/product46.jpg", description: "سمك مرجان طازج من أعماق البحر" },
    { id: 47, name: "سمك باراكودا", category: "fish", image: "images/product47.jpg", description: "سمك باراكودا طازج بطعم قوي مميز" },
    { id: 48, name: "سمك جروبر", category: "fish", image: "images/product48.jpg", description: "سمك جروبر كبير طازج عالي الجودة" },
    { id: 49, name: "سمك أمبرجاك", category: "fish", image: "images/product49.jpg", description: "سمك أمبرجاك طازج غني بالبروتين" },
    { id: 50, name: "سمك فلوندر", category: "fish", image: "images/product50.jpg", description: "سمك فلوندر المسطح طازج ولذيذ" },
    { id: 51, name: "سمك تيلابيا", category: "fish", image: "images/product51.jpg", description: "سمك تيلابيا طازج سهل التحضير" },
    { id: 52, name: "سمك كاتفيش", category: "fish", image: "images/product52.jpg", description: "سمك كاتفيش طازج بلحم أبيض ناعم" },
    { id: 53, name: "سمك ترويت", category: "fish", image: "images/product53.jpg", description: "سمك ترويت طازج من المياه الباردة" },
    { id: 54, name: "سمك باس البحر", category: "fish", image: "images/product54.jpg", description: "سمك باس البحر طازج عالي الجودة" },
    { id: 55, name: "سمك بومبانو", category: "fish", image: "images/product55.jpg", description: "سمك بومبانو الفضي طازج ولذيذ" },
    { id: 56, name: "سمك كينج فيش", category: "fish", image: "images/product56.jpg", description: "سمك كينج فيش الملكي طازج" },
    { id: 57, name: "سمك واهو", category: "fish", image: "images/product57.jpg", description: "سمك واهو السريع طازج من المحيط" },
    { id: 58, name: "سمك دولفين", category: "fish", image: "images/product58.jpg", description: "سمك دولفين (ماهي ماهي) طازج" },
    { id: 59, name: "سمك تونا الزعنفة الصفراء", category: "fish", image: "images/product59.jpg", description: "تونا الزعنفة الصفراء طازجة للسوشي" },
    { id: 60, name: "سمك مولت", category: "fish", image: "images/product60.jpg", description: "سمك مولت الصغير طازج للقلي" },

    // Squid Products (61-80)
    { id: 61, name: "كاليماري طازج كبير", category: "squid", image: "images/product61.jpg", description: "كاليماري طازج كبير الحجم مثالي للحشو" },
    { id: 62, name: "كاليماري حلقات", category: "squid", image: "images/product62.jpg", description: "حلقات كاليماري جاهزة للقلي والتقديم" },
    { id: 63, name: "كاليماري مقطع شرائح", category: "squid", image: "images/product63.jpg", description: "كاليماري مقطع شرائح جاهز للطبخ" },
    { id: 64, name: "كاليماري محشي", category: "squid", image: "images/product64.jpg", description: "كاليماري محشي بالأرز والخضار" },
    { id: 65, name: "كاليماري مقلي مقرمش", category: "squid", image: "images/product65.jpg", description: "كاليماري مقلي مقرمش جاهز للتقديم" },
    { id: 66, name: "كاليماري بالثوم", category: "squid", image: "images/product66.jpg", description: "كاليماري متبل بالثوم والبقدونس" },
    { id: 67, name: "كاليماري للسلطة", category: "squid", image: "images/product67.jpg", description: "كاليماري صغير مسلوق للسلطات" },
    { id: 68, name: "كاليماري مدخن", category: "squid", image: "images/product68.jpg", description: "كاليماري مدخن بطريقة تقليدية" },
    { id: 69, name: "كاليماري بالحبر", category: "squid", image: "images/product69.jpg", description: "كاليماري طازج مع الحبر الطبيعي" },
    { id: 70, name: "كاليماري للباستا", category: "squid", image: "images/product70.jpg", description: "كاليماري مقطع مثالي لأطباق الباستا" },
    { id: 71, name: "أخطبوط طازج كبير", category: "squid", image: "images/product71.jpg", description: "أخطبوط طازج كبير عالي الجودة" },
    { id: 72, name: "أخطبوط صغير", category: "squid", image: "images/product72.jpg", description: "أخطبوط صغير طازج للسلطات" },
    { id: 73, name: "أخطبوط مسلوق", category: "squid", image: "images/product73.jpg", description: "أخطبوط مسلوق جاهز للتقديم" },
    { id: 74, name: "أخطبوط مشوي", category: "squid", image: "images/product74.jpg", description: "أخطبوط مشوي بالأعشاب والليمون" },
    { id: 75, name: "أخطبوط بالزيت والخل", category: "squid", image: "images/product75.jpg", description: "أخطبوط متبل بالزيت والخل" },
    { id: 76, name: "كاليماري جامبو", category: "squid", image: "images/product76.jpg", description: "كاليماري جامبو كبير الحجم فاخر" },
    { id: 77, name: "كاليماري بالليمون", category: "squid", image: "images/product77.jpg", description: "كاليماري طازج متبل بالليمون" },
    { id: 78, name: "كاليماري للشوي", category: "squid", image: "images/product78.jpg", description: "كاليماري كامل مثالي للشوي" },
    { id: 79, name: "أخطبوط بالطماطم", category: "squid", image: "images/product79.jpg", description: "أخطبوط مطبوخ بصلصة الطماطم" },
    { id: 80, name: "كاليماري بالفلفل", category: "squid", image: "images/product80.jpg", description: "كاليماري متبل بالفلفل الحار" },

    // Crab & Lobster Products (81-95)
    { id: 81, name: "استاكوزا طازجة كبيرة", category: "crab-lobster", image: "images/product81.jpg", description: "استاكوزا طازجة كبيرة الحجم فاخرة" },
    { id: 82, name: "استاكوزا متوسطة", category: "crab-lobster", image: "images/product82.jpg", description: "استاكوزا متوسطة الحجم طازجة" },
    { id: 83, name: "ذيل استاكوزا", category: "crab-lobster", image: "images/product83.jpg", description: "ذيل استاكوزا طازج بدون قشر" },
    { id: 84, name: "استاكوزا مسلوقة", category: "crab-lobster", image: "images/product84.jpg", description: "استاكوزا مسلوقة جاهزة للتقديم" },
    { id: 85, name: "استاكوزا مشوية", category: "crab-lobster", image: "images/product85.jpg", description: "استاكوزا مشوية بالزبدة والثوم" },
    { id: 86, name: "سلطعون طازج", category: "crab-lobster", image: "images/product86.jpg", description: "سلطعون طازج عالي الجودة" },
    { id: 87, name: "سلطعون أزرق", category: "crab-lobster", image: "images/product87.jpg", description: "سلطعون أزرق طازج من البحر" },
    { id: 88, name: "لحم سلطعون", category: "crab-lobster", image: "images/product88.jpg", description: "لحم سلطعون طازج منزوع القشر" },
    { id: 89, name: "سلطعون ناعم القشرة", category: "crab-lobster", image: "images/product89.jpg", description: "سلطعون ناعم القشرة للقلي" },
    { id: 90, name: "استاكوزا صخرية", category: "crab-lobster", image: "images/product90.jpg", description: "استاكوزا صخرية طازجة فاخرة" },
    { id: 91, name: "سلطعون كينج", category: "crab-lobster", image: "images/product91.jpg", description: "سلطعون كينج كبير الحجم" },
    { id: 92, name: "أرجل سلطعون", category: "crab-lobster", image: "images/product92.jpg", description: "أرجل سلطعون طازجة مقطعة" },
    { id: 93, name: "استاكوزا حمراء", category: "crab-lobster", image: "images/product93.jpg", description: "استاكوزا حمراء طازجة مميزة" },
    { id: 94, name: "سلطعون للسلطة", category: "crab-lobster", image: "images/product94.jpg", description: "لحم سلطعون للسلطات والمقبلات" },
    { id: 95, name: "استاكوزا بالزبدة", category: "crab-lobster", image: "images/product95.jpg", description: "استاكوزا مطبوخة بالزبدة والأعشاب" },

    // Herring & Pickled Fish (96-105)
    { id: 96, name: "رنجة مملحة تقليدية", category: "herring", image: "images/product96.jpg", description: "رنجة مملحة بالطريقة التقليدية المصرية" },
    { id: 97, name: "فسيخ بلدي", category: "herring", image: "images/product97.jpg", description: "فسيخ بلدي أصلي عالي الجودة" },
    { id: 98, name: "رنجة مدخنة", category: "herring", image: "images/product98.jpg", description: "رنجة مدخنة بطريقة احترافية" },
    { id: 99, name: "فسيخ فاخر", category: "herring", image: "images/product99.jpg", description: "فسيخ فاخر للمناسبات الخاصة" },
    { id: 100, name: "رنجة بالزيت", category: "herring", image: "images/product100.jpg", description: "رنجة محفوظة بزيت الزيتون" },
    { id: 101, name: "فسيخ مقطع", category: "herring", image: "images/product101.jpg", description: "فسيخ مقطع جاهز للتقديم" },
    { id: 102, name: "رنجة هولندية", category: "herring", image: "images/product102.jpg", description: "رنجة هولندية مستوردة عالية الجودة" },
    { id: 103, name: "فسيخ بالليمون", category: "herring", image: "images/product103.jpg", description: "فسيخ متبل بالليمون والبصل" },
    { id: 104, name: "رنجة للفطار", category: "herring", image: "images/product104.jpg", description: "رنجة مقطعة جاهزة للفطار" },
    { id: 105, name: "فسيخ ملوكي", category: "herring", image: "images/product105.jpg", description: "فسيخ ملوكي فاخر للضيافة" },

    // Salmon Products (106-110)
    { id: 106, name: "سلمون نرويجي طازج", category: "salmon", image: "images/product106.jpg", description: "سلمون نرويجي طازج عالي الجودة" },
    { id: 107, name: "فيليه سلمون", category: "salmon", image: "images/product107.jpg", description: "فيليه سلمون طازج بدون عظم" },
    { id: 108, name: "سلمون مدخن", category: "salmon", image: "images/product108.jpg", description: "سلمون مدخن فاخر للمقبلات" },
    { id: 109, name: "سلمون للسوشي", category: "salmon", image: "images/product109.jpg", description: "سلمون طازج عالي الجودة للسوشي" },
    { id: 110, name: "سلمون مشوي", category: "salmon", image: "images/product110.jpg", description: "سلمون مشوي بالأعشاب والليمون" },

    // Miscellaneous Products (111-115)
    { id: 111, name: "بلح البحر", category: "miscellaneous", image: "images/product111.jpg", description: "بلح البحر الطازج عالي الجودة" },
    { id: 112, name: "محار طازج", category: "miscellaneous", image: "images/product112.jpg", description: "محار طازج من أفضل المصادر" },
    { id: 113, name: "قنديل البحر", category: "miscellaneous", image: "images/product113.jpg", description: "قنديل البحر الطازج للأطباق الآسيوية" },
    { id: 114, name: "خيار البحر", category: "miscellaneous", image: "images/product114.jpg", description: "خيار البحر الطازج عالي القيمة الغذائية" },
    { id: 115, name: "طحالب بحرية", category: "miscellaneous", image: "images/product115.jpg", description: "طحالب بحرية طازجة غنية بالمعادن" }
];
